# Install script for directory: E:/opencv/opencv/sources/modules

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "E:/opencv/VS opencv3.0 project_vs2015/install")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/calib3d/.calib3d/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/core/.core/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudaarithm/.cudaarithm/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudabgsegm/.cudabgsegm/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudacodec/.cudacodec/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudafeatures2d/.cudafeatures2d/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudafilters/.cudafilters/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudaimgproc/.cudaimgproc/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudalegacy/.cudalegacy/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudaobjdetect/.cudaobjdetect/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudaoptflow/.cudaoptflow/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudastereo/.cudastereo/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudawarping/.cudawarping/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudev/.cudev/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/features2d/.features2d/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/flann/.flann/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/hal/.hal/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/highgui/.highgui/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/imgcodecs/.imgcodecs/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/imgproc/.imgproc/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/java/.java/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/ml/.ml/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/objdetect/.objdetect/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/photo/.photo/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/python/.python/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/shape/.shape/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/stitching/.stitching/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/superres/.superres/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/ts/.ts/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/video/.video/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/videoio/.videoio/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/videostab/.videostab/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/viz/.viz/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/world/.world/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/adas/.adas/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/bgsegm/.bgsegm/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/bioinspired/.bioinspired/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/ccalib/.ccalib/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/contrib_world/.contrib_world/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cvv/.cvv/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/datasets/.datasets/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/face/.face/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/latentsvm/.latentsvm/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/line_descriptor/.line_descriptor/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/matlab/.matlab/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/optflow/.optflow/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/reg/.reg/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/rgbd/.rgbd/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/saliency/.saliency/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/surface_matching/.surface_matching/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/text/.text/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/tracking/.tracking/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/xfeatures2d/.xfeatures2d/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/ximgproc/.ximgproc/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/xobjdetect/.xobjdetect/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/xphoto/.xphoto/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/hal/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudev/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/core/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudaarithm/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/flann/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/imgproc/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/ml/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/reg/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/surface_matching/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/video/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudabgsegm/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudafilters/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudaimgproc/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudawarping/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/face/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/imgcodecs/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/photo/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/shape/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/videoio/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudacodec/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/highgui/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/objdetect/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/optflow/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/tracking/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/ts/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/ximgproc/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/xobjdetect/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/xphoto/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/adas/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/bgsegm/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/bioinspired/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/features2d/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/latentsvm/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/line_descriptor/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/saliency/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/text/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/calib3d/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/ccalib/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudafeatures2d/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudalegacy/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudaobjdetect/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudaoptflow/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/cudastereo/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/datasets/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/rgbd/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/superres/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/videostab/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/xfeatures2d/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/stitching/cmake_install.cmake")
  include("E:/opencv/VS opencv3.0 project_vs2015/modules/python3/cmake_install.cmake")

endif()

