# Generated by CMake 3.6.2

if("${CMAKE_MAJOR_VERSION}.${CMAKE_MINOR_VERSION}" LESS 2.5)
   message(FATAL_ERROR "CMake >= 2.6.0 required")
endif()
cmake_policy(PUSH)
cmake_policy(VERSION 2.6)
#----------------------------------------------------------------
# Generated CMake target import file.
#----------------------------------------------------------------

# Commands may need to know the format version.
set(CMAKE_IMPORT_FILE_VERSION 1)

# Protect against multiple inclusion, which would fail when already imported targets are added once more.
set(_targetsDefined)
set(_targetsNotDefined)
set(_expectedTargets)
foreach(_expectedTarget opencv_hal opencv_cudev opencv_core opencv_cudaarithm opencv_flann opencv_imgproc opencv_ml opencv_reg opencv_surface_matching opencv_video opencv_cudabgsegm opencv_cudafilters opencv_cudaimgproc opencv_cudawarping opencv_face opencv_imgcodecs opencv_photo opencv_shape opencv_videoio opencv_cudacodec opencv_highgui opencv_objdetect opencv_optflow opencv_tracking opencv_ts opencv_ximgproc opencv_xobjdetect opencv_xphoto opencv_adas opencv_bgsegm opencv_bioinspired opencv_features2d opencv_latentsvm opencv_line_descriptor opencv_saliency opencv_text opencv_calib3d opencv_ccalib opencv_cudafeatures2d opencv_cudalegacy opencv_cudaobjdetect opencv_cudaoptflow opencv_cudastereo opencv_datasets opencv_rgbd opencv_superres opencv_videostab opencv_xfeatures2d opencv_stitching)
  list(APPEND _expectedTargets ${_expectedTarget})
  if(NOT TARGET ${_expectedTarget})
    list(APPEND _targetsNotDefined ${_expectedTarget})
  endif()
  if(TARGET ${_expectedTarget})
    list(APPEND _targetsDefined ${_expectedTarget})
  endif()
endforeach()
if("${_targetsDefined}" STREQUAL "${_expectedTargets}")
  unset(_targetsDefined)
  unset(_targetsNotDefined)
  unset(_expectedTargets)
  set(CMAKE_IMPORT_FILE_VERSION)
  cmake_policy(POP)
  return()
endif()
if(NOT "${_targetsDefined}" STREQUAL "")
  message(FATAL_ERROR "Some (but not all) targets in this export set were already defined.\nTargets Defined: ${_targetsDefined}\nTargets not yet defined: ${_targetsNotDefined}\n")
endif()
unset(_targetsDefined)
unset(_targetsNotDefined)
unset(_expectedTargets)


# Create imported target opencv_hal
add_library(opencv_hal STATIC IMPORTED)

# Create imported target opencv_cudev
add_library(opencv_cudev SHARED IMPORTED)

# Create imported target opencv_core
add_library(opencv_core SHARED IMPORTED)

# Create imported target opencv_cudaarithm
add_library(opencv_cudaarithm SHARED IMPORTED)

# Create imported target opencv_flann
add_library(opencv_flann SHARED IMPORTED)

# Create imported target opencv_imgproc
add_library(opencv_imgproc SHARED IMPORTED)

# Create imported target opencv_ml
add_library(opencv_ml SHARED IMPORTED)

# Create imported target opencv_reg
add_library(opencv_reg SHARED IMPORTED)

# Create imported target opencv_surface_matching
add_library(opencv_surface_matching SHARED IMPORTED)

# Create imported target opencv_video
add_library(opencv_video SHARED IMPORTED)

# Create imported target opencv_cudabgsegm
add_library(opencv_cudabgsegm SHARED IMPORTED)

# Create imported target opencv_cudafilters
add_library(opencv_cudafilters SHARED IMPORTED)

# Create imported target opencv_cudaimgproc
add_library(opencv_cudaimgproc SHARED IMPORTED)

# Create imported target opencv_cudawarping
add_library(opencv_cudawarping SHARED IMPORTED)

# Create imported target opencv_face
add_library(opencv_face SHARED IMPORTED)

# Create imported target opencv_imgcodecs
add_library(opencv_imgcodecs SHARED IMPORTED)

# Create imported target opencv_photo
add_library(opencv_photo SHARED IMPORTED)

# Create imported target opencv_shape
add_library(opencv_shape SHARED IMPORTED)

# Create imported target opencv_videoio
add_library(opencv_videoio SHARED IMPORTED)

# Create imported target opencv_cudacodec
add_library(opencv_cudacodec SHARED IMPORTED)

# Create imported target opencv_highgui
add_library(opencv_highgui SHARED IMPORTED)

# Create imported target opencv_objdetect
add_library(opencv_objdetect SHARED IMPORTED)

# Create imported target opencv_optflow
add_library(opencv_optflow SHARED IMPORTED)

# Create imported target opencv_tracking
add_library(opencv_tracking SHARED IMPORTED)

# Create imported target opencv_ts
add_library(opencv_ts STATIC IMPORTED)

# Create imported target opencv_ximgproc
add_library(opencv_ximgproc SHARED IMPORTED)

# Create imported target opencv_xobjdetect
add_library(opencv_xobjdetect SHARED IMPORTED)

# Create imported target opencv_xphoto
add_library(opencv_xphoto SHARED IMPORTED)

# Create imported target opencv_adas
add_library(opencv_adas SHARED IMPORTED)

# Create imported target opencv_bgsegm
add_library(opencv_bgsegm SHARED IMPORTED)

# Create imported target opencv_bioinspired
add_library(opencv_bioinspired SHARED IMPORTED)

# Create imported target opencv_features2d
add_library(opencv_features2d SHARED IMPORTED)

# Create imported target opencv_latentsvm
add_library(opencv_latentsvm SHARED IMPORTED)

# Create imported target opencv_line_descriptor
add_library(opencv_line_descriptor SHARED IMPORTED)

# Create imported target opencv_saliency
add_library(opencv_saliency SHARED IMPORTED)

# Create imported target opencv_text
add_library(opencv_text SHARED IMPORTED)

# Create imported target opencv_calib3d
add_library(opencv_calib3d SHARED IMPORTED)

# Create imported target opencv_ccalib
add_library(opencv_ccalib SHARED IMPORTED)

# Create imported target opencv_cudafeatures2d
add_library(opencv_cudafeatures2d SHARED IMPORTED)

# Create imported target opencv_cudalegacy
add_library(opencv_cudalegacy SHARED IMPORTED)

# Create imported target opencv_cudaobjdetect
add_library(opencv_cudaobjdetect SHARED IMPORTED)

# Create imported target opencv_cudaoptflow
add_library(opencv_cudaoptflow SHARED IMPORTED)

# Create imported target opencv_cudastereo
add_library(opencv_cudastereo SHARED IMPORTED)

# Create imported target opencv_datasets
add_library(opencv_datasets SHARED IMPORTED)

# Create imported target opencv_rgbd
add_library(opencv_rgbd SHARED IMPORTED)

# Create imported target opencv_superres
add_library(opencv_superres SHARED IMPORTED)

# Create imported target opencv_videostab
add_library(opencv_videostab SHARED IMPORTED)

# Create imported target opencv_xfeatures2d
add_library(opencv_xfeatures2d SHARED IMPORTED)

# Create imported target opencv_stitching
add_library(opencv_stitching SHARED IMPORTED)

# Import target "opencv_hal" for configuration "Debug"
set_property(TARGET opencv_hal APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_hal PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "ippicv;cudart;nppc;nppi;npps;cufft;cudart;nppc;nppi;npps"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_hal300d.lib"
  )

# Import target "opencv_cudev" for configuration "Debug"
set_property(TARGET opencv_cudev APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudev PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_cudev300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_cudev300d.dll"
  )

# Import target "opencv_core" for configuration "Debug"
set_property(TARGET opencv_core APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_core PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_core300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_core300d.dll"
  )

# Import target "opencv_cudaarithm" for configuration "Debug"
set_property(TARGET opencv_cudaarithm APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudaarithm PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_cudaarithm300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_cudaarithm300d.dll"
  )

# Import target "opencv_flann" for configuration "Debug"
set_property(TARGET opencv_flann APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_flann PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_flann300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_flann300d.dll"
  )

# Import target "opencv_imgproc" for configuration "Debug"
set_property(TARGET opencv_imgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_imgproc PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_imgproc300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_imgproc300d.dll"
  )

# Import target "opencv_ml" for configuration "Debug"
set_property(TARGET opencv_ml APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_ml PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_ml300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_ml300d.dll"
  )

# Import target "opencv_reg" for configuration "Debug"
set_property(TARGET opencv_reg APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_reg PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_reg300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_reg300d.dll"
  )

# Import target "opencv_surface_matching" for configuration "Debug"
set_property(TARGET opencv_surface_matching APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_surface_matching PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_surface_matching300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_flann"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_surface_matching300d.dll"
  )

# Import target "opencv_video" for configuration "Debug"
set_property(TARGET opencv_video APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_video PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_video300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_video300d.dll"
  )

# Import target "opencv_cudabgsegm" for configuration "Debug"
set_property(TARGET opencv_cudabgsegm APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudabgsegm PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_cudabgsegm300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_video"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_cudabgsegm300d.dll"
  )

# Import target "opencv_cudafilters" for configuration "Debug"
set_property(TARGET opencv_cudafilters APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudafilters PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_cudafilters300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_imgproc"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_cudafilters300d.dll"
  )

# Import target "opencv_cudaimgproc" for configuration "Debug"
set_property(TARGET opencv_cudaimgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudaimgproc PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_cudaimgproc300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_imgproc;opencv_cudafilters"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_cudaimgproc300d.dll"
  )

# Import target "opencv_cudawarping" for configuration "Debug"
set_property(TARGET opencv_cudawarping APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudawarping PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_cudawarping300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_cudawarping300d.dll"
  )

# Import target "opencv_face" for configuration "Debug"
set_property(TARGET opencv_face APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_face PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_face300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_face300d.dll"
  )

# Import target "opencv_imgcodecs" for configuration "Debug"
set_property(TARGET opencv_imgcodecs APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_imgcodecs PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_imgcodecs300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_imgcodecs300d.dll"
  )

# Import target "opencv_photo" for configuration "Debug"
set_property(TARGET opencv_photo APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_photo PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_photo300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_photo300d.dll"
  )

# Import target "opencv_shape" for configuration "Debug"
set_property(TARGET opencv_shape APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_shape PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_shape300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_video"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_shape300d.dll"
  )

# Import target "opencv_videoio" for configuration "Debug"
set_property(TARGET opencv_videoio APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_videoio PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_videoio300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_videoio300d.dll"
  )

# Import target "opencv_cudacodec" for configuration "Debug"
set_property(TARGET opencv_cudacodec APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudacodec PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_cudacodec300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_cudacodec300d.dll"
  )

# Import target "opencv_highgui" for configuration "Debug"
set_property(TARGET opencv_highgui APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_highgui PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_highgui300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_highgui300d.dll"
  )

# Import target "opencv_objdetect" for configuration "Debug"
set_property(TARGET opencv_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_objdetect PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_objdetect300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_objdetect300d.dll"
  )

# Import target "opencv_optflow" for configuration "Debug"
set_property(TARGET opencv_optflow APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_optflow PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_optflow300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_video;opencv_imgcodecs;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_optflow300d.dll"
  )

# Import target "opencv_tracking" for configuration "Debug"
set_property(TARGET opencv_tracking APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_tracking PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_tracking300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_video;opencv_imgcodecs;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_tracking300d.dll"
  )

# Import target "opencv_ts" for configuration "Debug"
set_property(TARGET opencv_ts APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_ts PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_DEBUG "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;ippicv;cudart;nppc;nppi;npps;cufft;cudart;nppc;nppi;npps"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_ts300d.lib"
  )

# Import target "opencv_ximgproc" for configuration "Debug"
set_property(TARGET opencv_ximgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_ximgproc PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_ximgproc300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_ximgproc300d.dll"
  )

# Import target "opencv_xobjdetect" for configuration "Debug"
set_property(TARGET opencv_xobjdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_xobjdetect PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_xobjdetect300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_xobjdetect300d.dll"
  )

# Import target "opencv_xphoto" for configuration "Debug"
set_property(TARGET opencv_xphoto APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_xphoto PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_xphoto300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc;opencv_imgcodecs;opencv_photo;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_xphoto300d.dll"
  )

# Import target "opencv_adas" for configuration "Debug"
set_property(TARGET opencv_adas APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_adas PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_adas300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_xobjdetect"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_adas300d.dll"
  )

# Import target "opencv_bgsegm" for configuration "Debug"
set_property(TARGET opencv_bgsegm APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_bgsegm PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_bgsegm300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_video;opencv_imgcodecs;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_bgsegm300d.dll"
  )

# Import target "opencv_bioinspired" for configuration "Debug"
set_property(TARGET opencv_bioinspired APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_bioinspired PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_bioinspired300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_bioinspired300d.dll"
  )

# Import target "opencv_features2d" for configuration "Debug"
set_property(TARGET opencv_features2d APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_features2d PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_features2d300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_features2d300d.dll"
  )

# Import target "opencv_latentsvm" for configuration "Debug"
set_property(TARGET opencv_latentsvm APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_latentsvm PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_latentsvm300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_objdetect"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_latentsvm300d.dll"
  )

# Import target "opencv_line_descriptor" for configuration "Debug"
set_property(TARGET opencv_line_descriptor APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_line_descriptor PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_line_descriptor300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_line_descriptor300d.dll"
  )

# Import target "opencv_saliency" for configuration "Debug"
set_property(TARGET opencv_saliency APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_saliency PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_saliency300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_saliency300d.dll"
  )

# Import target "opencv_text" for configuration "Debug"
set_property(TARGET opencv_text APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_text PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_text300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_text300d.dll"
  )

# Import target "opencv_calib3d" for configuration "Debug"
set_property(TARGET opencv_calib3d APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_calib3d PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_calib3d300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_calib3d300d.dll"
  )

# Import target "opencv_ccalib" for configuration "Debug"
set_property(TARGET opencv_ccalib APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_ccalib PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_ccalib300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_ccalib300d.dll"
  )

# Import target "opencv_cudafeatures2d" for configuration "Debug"
set_property(TARGET opencv_cudafeatures2d APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudafeatures2d PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_cudafeatures2d300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_cudafilters;opencv_cudawarping;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_cudafeatures2d300d.dll"
  )

# Import target "opencv_cudalegacy" for configuration "Debug"
set_property(TARGET opencv_cudalegacy APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudalegacy PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_cudalegacy300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_video;opencv_cudafilters;opencv_cudaimgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_objdetect;opencv_features2d;opencv_calib3d"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_cudalegacy300d.dll"
  )

# Import target "opencv_cudaobjdetect" for configuration "Debug"
set_property(TARGET opencv_cudaobjdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudaobjdetect PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_cudaobjdetect300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_video;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_objdetect;opencv_features2d;opencv_calib3d;opencv_cudalegacy"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_cudaobjdetect300d.dll"
  )

# Import target "opencv_cudaoptflow" for configuration "Debug"
set_property(TARGET opencv_cudaoptflow APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudaoptflow PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_cudaoptflow300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_video;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_objdetect;opencv_features2d;opencv_calib3d;opencv_cudalegacy"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_cudaoptflow300d.dll"
  )

# Import target "opencv_cudastereo" for configuration "Debug"
set_property(TARGET opencv_cudastereo APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_cudastereo PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_cudastereo300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_cudastereo300d.dll"
  )

# Import target "opencv_datasets" for configuration "Debug"
set_property(TARGET opencv_datasets APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_datasets PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_datasets300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_face;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_text"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_datasets300d.dll"
  )

# Import target "opencv_rgbd" for configuration "Debug"
set_property(TARGET opencv_rgbd APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_rgbd PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_rgbd300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_rgbd300d.dll"
  )

# Import target "opencv_superres" for configuration "Debug"
set_property(TARGET opencv_superres APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_superres PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_superres300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_video;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_imgcodecs;opencv_videoio;opencv_cudacodec;opencv_highgui;opencv_objdetect;opencv_features2d;opencv_calib3d;opencv_cudalegacy;opencv_cudaoptflow"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_superres300d.dll"
  )

# Import target "opencv_videostab" for configuration "Debug"
set_property(TARGET opencv_videostab APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_videostab PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_videostab300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_video;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_imgcodecs;opencv_photo;opencv_videoio;opencv_highgui;opencv_objdetect;opencv_features2d;opencv_calib3d;opencv_cudalegacy;opencv_cudaoptflow"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_videostab300d.dll"
  )

# Import target "opencv_xfeatures2d" for configuration "Debug"
set_property(TARGET opencv_xfeatures2d APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_xfeatures2d PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_xfeatures2d300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_video;opencv_imgcodecs;opencv_shape;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_xfeatures2d300d.dll"
  )

# Import target "opencv_stitching" for configuration "Debug"
set_property(TARGET opencv_stitching APPEND PROPERTY IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(opencv_stitching PROPERTIES
  IMPORTED_IMPLIB_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/lib/Debug/opencv_stitching300d.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_video;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_imgcodecs;opencv_shape;opencv_videoio;opencv_highgui;opencv_objdetect;opencv_features2d;opencv_calib3d;opencv_cudafeatures2d;opencv_cudalegacy;opencv_xfeatures2d"
  IMPORTED_LOCATION_DEBUG "E:/opencv/VS opencv3.0 project_vs2015/bin/Debug/opencv_stitching300d.dll"
  )

# Import target "opencv_hal" for configuration "Release"
set_property(TARGET opencv_hal APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_hal PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "ippicv;cudart;nppc;nppi;npps;cufft;cudart;nppc;nppi;npps"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_hal300.lib"
  )

# Import target "opencv_cudev" for configuration "Release"
set_property(TARGET opencv_cudev APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudev PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_cudev300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_cudev300.dll"
  )

# Import target "opencv_core" for configuration "Release"
set_property(TARGET opencv_core APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_core PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_core300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_core300.dll"
  )

# Import target "opencv_cudaarithm" for configuration "Release"
set_property(TARGET opencv_cudaarithm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudaarithm PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_cudaarithm300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_cudaarithm300.dll"
  )

# Import target "opencv_flann" for configuration "Release"
set_property(TARGET opencv_flann APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_flann PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_flann300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_flann300.dll"
  )

# Import target "opencv_imgproc" for configuration "Release"
set_property(TARGET opencv_imgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_imgproc PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_imgproc300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_imgproc300.dll"
  )

# Import target "opencv_ml" for configuration "Release"
set_property(TARGET opencv_ml APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_ml PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_ml300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_ml300.dll"
  )

# Import target "opencv_reg" for configuration "Release"
set_property(TARGET opencv_reg APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_reg PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_reg300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_reg300.dll"
  )

# Import target "opencv_surface_matching" for configuration "Release"
set_property(TARGET opencv_surface_matching APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_surface_matching PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_surface_matching300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_flann"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_surface_matching300.dll"
  )

# Import target "opencv_video" for configuration "Release"
set_property(TARGET opencv_video APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_video PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_video300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_video300.dll"
  )

# Import target "opencv_cudabgsegm" for configuration "Release"
set_property(TARGET opencv_cudabgsegm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudabgsegm PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_cudabgsegm300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_video"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_cudabgsegm300.dll"
  )

# Import target "opencv_cudafilters" for configuration "Release"
set_property(TARGET opencv_cudafilters APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudafilters PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_cudafilters300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_imgproc"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_cudafilters300.dll"
  )

# Import target "opencv_cudaimgproc" for configuration "Release"
set_property(TARGET opencv_cudaimgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudaimgproc PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_cudaimgproc300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_imgproc;opencv_cudafilters"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_cudaimgproc300.dll"
  )

# Import target "opencv_cudawarping" for configuration "Release"
set_property(TARGET opencv_cudawarping APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudawarping PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_cudawarping300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_cudawarping300.dll"
  )

# Import target "opencv_face" for configuration "Release"
set_property(TARGET opencv_face APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_face PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_face300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_face300.dll"
  )

# Import target "opencv_imgcodecs" for configuration "Release"
set_property(TARGET opencv_imgcodecs APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_imgcodecs PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_imgcodecs300.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_imgproc"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_imgcodecs300.dll"
  )

# Import target "opencv_photo" for configuration "Release"
set_property(TARGET opencv_photo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_photo PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_photo300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_photo300.dll"
  )

# Import target "opencv_shape" for configuration "Release"
set_property(TARGET opencv_shape APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_shape PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_shape300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_video"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_shape300.dll"
  )

# Import target "opencv_videoio" for configuration "Release"
set_property(TARGET opencv_videoio APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_videoio PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_videoio300.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_videoio300.dll"
  )

# Import target "opencv_cudacodec" for configuration "Release"
set_property(TARGET opencv_cudacodec APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudacodec PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_cudacodec300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_cudacodec300.dll"
  )

# Import target "opencv_highgui" for configuration "Release"
set_property(TARGET opencv_highgui APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_highgui PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_highgui300.lib"
  IMPORTED_LINK_DEPENDENT_LIBRARIES_RELEASE "opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE ""
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_highgui300.dll"
  )

# Import target "opencv_objdetect" for configuration "Release"
set_property(TARGET opencv_objdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_objdetect PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_objdetect300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_objdetect300.dll"
  )

# Import target "opencv_optflow" for configuration "Release"
set_property(TARGET opencv_optflow APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_optflow PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_optflow300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_video;opencv_imgcodecs;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_optflow300.dll"
  )

# Import target "opencv_tracking" for configuration "Release"
set_property(TARGET opencv_tracking APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_tracking PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_tracking300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_video;opencv_imgcodecs;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_tracking300.dll"
  )

# Import target "opencv_ts" for configuration "Release"
set_property(TARGET opencv_ts APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_ts PROPERTIES
  IMPORTED_LINK_INTERFACE_LANGUAGES_RELEASE "CXX"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;ippicv;cudart;nppc;nppi;npps;cufft;cudart;nppc;nppi;npps"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_ts300.lib"
  )

# Import target "opencv_ximgproc" for configuration "Release"
set_property(TARGET opencv_ximgproc APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_ximgproc PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_ximgproc300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_ximgproc300.dll"
  )

# Import target "opencv_xobjdetect" for configuration "Release"
set_property(TARGET opencv_xobjdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_xobjdetect PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_xobjdetect300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_xobjdetect300.dll"
  )

# Import target "opencv_xphoto" for configuration "Release"
set_property(TARGET opencv_xphoto APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_xphoto PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_xphoto300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_imgproc;opencv_cudafilters;opencv_cudaimgproc;opencv_imgcodecs;opencv_photo;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_xphoto300.dll"
  )

# Import target "opencv_adas" for configuration "Release"
set_property(TARGET opencv_adas APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_adas PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_adas300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_xobjdetect"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_adas300.dll"
  )

# Import target "opencv_bgsegm" for configuration "Release"
set_property(TARGET opencv_bgsegm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_bgsegm PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_bgsegm300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_video;opencv_imgcodecs;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_bgsegm300.dll"
  )

# Import target "opencv_bioinspired" for configuration "Release"
set_property(TARGET opencv_bioinspired APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_bioinspired PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_bioinspired300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_bioinspired300.dll"
  )

# Import target "opencv_features2d" for configuration "Release"
set_property(TARGET opencv_features2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_features2d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_features2d300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_features2d300.dll"
  )

# Import target "opencv_latentsvm" for configuration "Release"
set_property(TARGET opencv_latentsvm APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_latentsvm PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_latentsvm300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_objdetect"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_latentsvm300.dll"
  )

# Import target "opencv_line_descriptor" for configuration "Release"
set_property(TARGET opencv_line_descriptor APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_line_descriptor PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_line_descriptor300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_line_descriptor300.dll"
  )

# Import target "opencv_saliency" for configuration "Release"
set_property(TARGET opencv_saliency APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_saliency PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_saliency300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_saliency300.dll"
  )

# Import target "opencv_text" for configuration "Release"
set_property(TARGET opencv_text APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_text PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_text300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_text300.dll"
  )

# Import target "opencv_calib3d" for configuration "Release"
set_property(TARGET opencv_calib3d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_calib3d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_calib3d300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_calib3d300.dll"
  )

# Import target "opencv_ccalib" for configuration "Release"
set_property(TARGET opencv_ccalib APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_ccalib PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_ccalib300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_ccalib300.dll"
  )

# Import target "opencv_cudafeatures2d" for configuration "Release"
set_property(TARGET opencv_cudafeatures2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudafeatures2d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_cudafeatures2d300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_cudafilters;opencv_cudawarping;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_cudafeatures2d300.dll"
  )

# Import target "opencv_cudalegacy" for configuration "Release"
set_property(TARGET opencv_cudalegacy APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudalegacy PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_cudalegacy300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_video;opencv_cudafilters;opencv_cudaimgproc;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_objdetect;opencv_features2d;opencv_calib3d"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_cudalegacy300.dll"
  )

# Import target "opencv_cudaobjdetect" for configuration "Release"
set_property(TARGET opencv_cudaobjdetect APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudaobjdetect PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_cudaobjdetect300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_video;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_objdetect;opencv_features2d;opencv_calib3d;opencv_cudalegacy"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_cudaobjdetect300.dll"
  )

# Import target "opencv_cudaoptflow" for configuration "Release"
set_property(TARGET opencv_cudaoptflow APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudaoptflow PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_cudaoptflow300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_video;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_objdetect;opencv_features2d;opencv_calib3d;opencv_cudalegacy"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_cudaoptflow300.dll"
  )

# Import target "opencv_cudastereo" for configuration "Release"
set_property(TARGET opencv_cudastereo APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_cudastereo PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_cudastereo300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_cudastereo300.dll"
  )

# Import target "opencv_datasets" for configuration "Release"
set_property(TARGET opencv_datasets APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_datasets PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_datasets300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_face;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_text"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_datasets300.dll"
  )

# Import target "opencv_rgbd" for configuration "Release"
set_property(TARGET opencv_rgbd APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_rgbd PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_rgbd300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_flann;opencv_imgproc;opencv_ml;opencv_imgcodecs;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_rgbd300.dll"
  )

# Import target "opencv_superres" for configuration "Release"
set_property(TARGET opencv_superres APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_superres PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_superres300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_video;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_imgcodecs;opencv_videoio;opencv_cudacodec;opencv_highgui;opencv_objdetect;opencv_features2d;opencv_calib3d;opencv_cudalegacy;opencv_cudaoptflow"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_superres300.dll"
  )

# Import target "opencv_videostab" for configuration "Release"
set_property(TARGET opencv_videostab APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_videostab PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_videostab300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_video;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_imgcodecs;opencv_photo;opencv_videoio;opencv_highgui;opencv_objdetect;opencv_features2d;opencv_calib3d;opencv_cudalegacy;opencv_cudaoptflow"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_videostab300.dll"
  )

# Import target "opencv_xfeatures2d" for configuration "Release"
set_property(TARGET opencv_xfeatures2d APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_xfeatures2d PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_xfeatures2d300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_video;opencv_imgcodecs;opencv_shape;opencv_videoio;opencv_highgui;opencv_features2d;opencv_calib3d"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_xfeatures2d300.dll"
  )

# Import target "opencv_stitching" for configuration "Release"
set_property(TARGET opencv_stitching APPEND PROPERTY IMPORTED_CONFIGURATIONS RELEASE)
set_target_properties(opencv_stitching PROPERTIES
  IMPORTED_IMPLIB_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/lib/Release/opencv_stitching300.lib"
  IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE "opencv_hal;opencv_cudev;opencv_core;opencv_cudaarithm;opencv_flann;opencv_imgproc;opencv_ml;opencv_video;opencv_cudafilters;opencv_cudaimgproc;opencv_cudawarping;opencv_imgcodecs;opencv_shape;opencv_videoio;opencv_highgui;opencv_objdetect;opencv_features2d;opencv_calib3d;opencv_cudafeatures2d;opencv_cudalegacy;opencv_xfeatures2d"
  IMPORTED_LOCATION_RELEASE "E:/opencv/VS opencv3.0 project_vs2015/bin/Release/opencv_stitching300.dll"
  )

# This file does not depend on other imported targets which have
# been exported from the same project but in a separate export set.

# Commands beyond this point should not need to know the version.
set(CMAKE_IMPORT_FILE_VERSION)
cmake_policy(POP)
